services:
  tambola-server:
    build: ./app
    container_name: tambola_online_board
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - tambola_net

  nginx:
    image: nginx:alpine
    container_name: tambola_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tambola-server
    restart: unless-stopped
    networks:
      - tambola_net

networks:
  tambola_net:
    driver: bridge
